### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Reasion** [zry656565/SJTU-Bus#35]
The arrive time of some stations are updated.
For the ME station, the new time is 5 minutes later than this Web app.

**Comment by hebingchang** [comment]
Hi reasion,

Thanks for report. This repo is not actively maintained now, so we will appreciate it a lot if you could create a merge request to update these data.

If you just want to check the bus schedule, you can alternatively use https://bus.sjtu.edu.cn.

**Comment by Reasionlee** [comment]
> Hi reasion,
> 
> Thanks for report. This repo is not actively maintained now, so we will appreciate it a lot if you could create a merge request to update these data.
> 
> If you just want to check the bus schedule, you can alternatively use https://bus.sjtu.edu.cn.

Thanks a lot.

I wish I could update these data by myself, but I have no experience on the php.

Sorry for that.
