### ISSUE TITLE
我们的校园app能直接引用到你的sinapp.com？

### ISSUE THREAD

**Issue by tq5124** [zry656565/SJTU-Bus#4]
你好，我们是sjtu东岳（算是技术社团吧），最近在开发一个校园app。我们本来也打算做校园bus的栏目，但是发现你这边已经有了~ 
我们的schoolBus栏目就能直接webview到你的http://sjtubus.sinaapp.com 吗？谢谢~

**Comment by zry656565** [comment]
没问题啊，就是不知道跟你们的app结合起来会不会有违和感。下个月有时间的话，我另外会添加一些功能。你们的app开源吗？

**Comment by tq5124** [comment]
那我们就先试试吧~
整个app应该不会开源的。。。

**Comment by zry656565** [comment]
嗯，好的。
